### ISSUE TITLE
Problem with lodash module

### ISSUE THREAD

**Issue by Fr4ncx** [MartyIce/generator-angular-fullstack-crud#10]
I have generated new app with "yo angular-fullstack" and then i have created the "config.json" file .
I did "yo angular-fullstack-crud" and now i'm getting the following errors : 

readline.js:924
            throw err;
            ^

Error: Cannot find module 'yeoman-generator/node_modules/lodash'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\Fr\AppData\Roaming\npm\node_modules\generator-angular-fullstack-crud\app\index.js:7:9)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)

Any suggestion?
Thanks

**Comment by azizasm** [comment]
I'm having the same  Error: Cannot find module 'yeoman-generator/node_modules/lodash'   error

**Comment by azizasm** [comment]
Managed to fix manully by : 
1) install loadash  : 
 `npm install -g lodash`  

2) and edit 
`%USERPROFILE%\AppData\Roaming\npm\node_modules\generator-angular-fullstack-crud\app\index.js`
and change from var _ = require('yeoman-generator/node_modules/lodash')
to  `var _ = require('lodash')`

**Comment by MartyIce** [comment]
Unfortunately, I haven't done much with this project for quite some time.  I can take pull requests (but won't be able to test much), or you can fork this repo if you want to move it forward.  Thanks!

**Comment by ghost** [comment]
Try doing everything again like this:
`npm install -g yo generator-angular-fullstack generator-angular-fullstack-crud`
